apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-avif-converter
  namespace: pv
  labels:
    app: pv-avif-converter
spec:
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pv-avif-converter
  template:
    metadata:
      labels:
        app: pv-avif-converter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pv-avif-converter
              topologyKey: kubernetes.io/hostname
      containers:
        - name: pv-avif-converter
          image: ghcr.io/ekskog/pv-converter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - secretRef:
                name: pv-api-secret
          env:
            - name: MINIO_ENDPOINT
              value: "192.168.1.8:9000"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 1800
            timeoutSeconds: 15
            failureThreshold: 2