apiVersion: v1
kind: Service
metadata:
  name: pv-imgproxy-service
  namespace: pv
  labels:
    app: pv-imgproxy
spec:
  selector:
    app: pv-imgproxy
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
